[ user {
    dataValues: 
     { id: 1,
       namn: 'exempelnamn1',
       text: 'exempeltext1',
       createdAt: 2019-07-20T20:51:46.000Z,
       updatedAt: 2019-07-20T20:51:46.000Z },
    _previousDataValues: 
     { id: 1,
       namn: 'exempelnamn1',
       text: 'exempeltext1',
       createdAt: 2019-07-20T20:51:46.000Z,
       updatedAt: 2019-07-20T20:51:46.000Z },
    _changed: {},
    _modelOptions: 
     { timestamps: true,
       validate: {},
       freezeTableName: false,
       underscored: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: {},
       indexes: [],
       name: [Object],
       omitNull: false,
       sequelize: [Object],
       hooks: {} },
    _options: 
     { isNewRecord: false,
       _schema: null,
       _schemaDelimiter: '',
       raw: true,
       attributes: [Array] },
    isNewRecord: false } ]